version: '3'
services:
  influxdb:
    image: qnib/plain-influxdb:1.2.4
    environment:
     - INFLUXDB_DATABASES=qframe
     - INFLUXDB_META_LOGGING=true
     - INFLUXDB_OPENTSDB_ENABLED=true
     - INFLUXDB_GRAPHITE_ENABLED=true
    volumes:
     - /opt/influxdb/shared
    ports:
     - 8083:8083
     - 8086:8086
  grafana:
    image: qnib/plain-grafana4
    ports:
     - 3000:3000
    environment:
     - INFLUXDB_HOST=qframe_influxdb
     - INFLUXDB_DB=qframe
    volumes:
      - ./resources/grafana/sql/dashboards/:/opt/grafana/sql/dashboards/
